##########################################################################
## Check if the local port url and public jennkins uri are up and running. 
## It considers 200 and 403 as success status
##########################################################################
- name: Check if local host URL is up and running
  uri:
    url: "http://{{ ansible_host }}:8080/"
    method: GET
    follow_redirects: none
    status_code: [200,403]
  register: result
  until: result.status in [200,403]
  retries: 5
  delay: 2

- name: Check if public host URL is up and running
  uri:
    url: "{{ jenkins_url }}"
    method: GET
    follow_redirects: none
    status_code: [200,403]
  register: result
  until: result.status in [200,403]
  retries: 5
  delay: 2
  when: jenkins_url is defined

